# Generated by Django 5.1.4 on 2025-01-15 11:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Amusement_Park_Application', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('nationality_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی/اتباع')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تلفن')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('role', models.CharField(choices=[('normal', 'عادی'), ('scanner', 'اسکنر'), ('kiosk', 'کیوسک')], default='normal', help_text='\n    |عادی :\u200c دسترسی به کل بخش های سایت|\n    |کیوسک :\u200c این دسترسی برای فروش از طریق ماشین تیکت تعریف شده|\n    |اسکنر :\u200c برای کارکنانی که وظیفه اسکن بارکد را دارند|\n    ', max_length=10, verbose_name='نقش کاربری')),
                ('categories', models.ManyToManyField(related_name='users', to='Amusement_Park_Application.category', verbose_name='دسته بندی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-update',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
