# Generated by Django 5.1.4 on 2024-12-23 12:50

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='نام خانوادگی')),
                ('nationality_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تلفن')),
                ('duty', models.CharField(blank=True, max_length=55, null=True, verbose_name='وظیفه')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='آدرس ایمیل')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True, verbose_name='کارمند')),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True, verbose_name='مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'permissions': [('can_view_user', 'می\u200cتواند کاربر را مشاهده کند'), ('can_edit_user', 'می\u200cتواند کاربر را ویرایش کند'), ('can_delete_user', 'می\u200cتواند کاربر را حذف کند')],
            },
        ),
    ]
