# Generated by Django 5.1.4 on 2024-12-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate_Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', 'عادی'), ('scanner', 'اسکنر'), ('kiosk', 'کیوسک')], default='normal', help_text='"\n    عادی :\u200c دسترسی به کل بخش های سایت\n    کیوسک :\u200c این دسترسی برای فروش از طریق ماشین تیکت طعریف شده\n    اسکنر :\u200c برای کارکنانی که وظیفه اسکن بارکد را دارند\n    ', max_length=10, verbose_name='نقش کاربری'),
        ),
    ]
