# Generated by Django 5.1.4 on 2024-12-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate_Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='به این گزینه دقت کنید زیرا اگر بله را انتخاب کنید این کاربر میتواند به این صفحه دسترسی داشته باشد (نکته :\u200c شما میتوانید گروه بندی کنید)', verbose_name='ادمین'),
        ),
    ]
