# Generated by Django 5.1.4 on 2025-01-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate_Application', '0002_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='این فیلد نشان می\u200cدهد که آیا کاربر باید به عنوان کارمند فعالیت کند .', verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='این فیلد نشان می\u200cدهد که آیا کاربر دسترسی کامل به تمامی بخش هارا دارد یا خیر.', verbose_name='ادمین'),
        ),
    ]
