# Generated by Django 5.1.4 on 2024-12-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate_Application', '0003_alter_myuser_date_of_birth_alter_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='به این گزینه دقت کنید زیرا اگر بله را انتخاب کنید این کاربر میتواند به این صفحه دسترسی داشته باشد', verbose_name='ادمین'),
        ),
    ]
