# Generated by Django 5.1.4 on 2025-01-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate_Application', '0003_alter_user_is_active_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='بجای حذف کاربر کافی است تیک این فیلد را بردارید تا این کاربر دیگر هیچ نوع دسترسی ای به وب اپلیکیشن نداشته باشد .', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='این فیلد نشان می\u200cدهد که آیا کاربر باید به عنوان کارمند فعالیت کند', verbose_name='کارمند'),
        ),
    ]
