# Generated by Django 5.1.4 on 2025-01-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate_Application', '0004_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', 'سوپر وایزر'), ('scanner', 'اسکنر'), ('kiosk', 'کیوسک')], default='normal', help_text='\n    |عادی :\u200c دسترسی به کل بخش های سایت|\n    |کیوسک :\u200c این دسترسی برای فروش از طریق ماشین تیکت تعریف شده|\n    |اسکنر :\u200c برای کارکنانی که وظیفه اسکن بارکد را دارند|\n    ', max_length=10, verbose_name='نقش کاربری'),
        ),
    ]
