# Generated by Django 5.1.4 on 2025-01-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate_Application', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='این فیلد نشان می\u200cدهد که آیا کاربر باید به عنوان کارمند فعالیت کند (اخطار : به کاربران کیوسک و اسکنر این دسترسی پیشنهاد نمیشود)', verbose_name='کارمند'),
        ),
    ]
