# Generated by Django 5.1.6 on 2025-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate_Application', '0008_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='این فیلد نشان می\u200cدهد که آیا کاربر باید به عنوان کارمند فعالیت کند (اخطار : به کاربران کیوسک و اسکنر این دسترسی را ندهید)', verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='این فیلد نشان می\u200cدهد که آیا کاربر دسترسی کامل به تمامی بخش هارا دارد یا خیر. (اخطار : به کاربران کیوسک و اسکنر این دسترسی را ندهید)', verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', 'دسترسی آزاد'), ('scanner', 'اسکنر'), ('kiosk', 'کیوسک')], default='normal', help_text='\n    عادی :\u200c دسترسی به کل بخش های سایت*****\n    *****کیوسک :\u200c این دسترسی برای فروش از طریق ماشین تیکت تعریف شده*****\n    *****اسکنر :\u200c برای کارکنانی که وظیفه اسکن بارکد را دارند\n    ', max_length=10, verbose_name='نقش کاربری'),
        ),
    ]
