# Generated by Django 5.1.4 on 2024-12-30 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True, verbose_name='نام محصول')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('tourist_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت توریستی')),
                ('image', models.ImageField(help_text='سایز 800*800', upload_to='product_image/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('is_taxable', models.BooleanField(default=False, verbose_name='مشمول مالیات بر ارزش افزوده')),
                ('order_metric', models.PositiveIntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=' زمان ایجاد')),
                ('update', models.DateTimeField(auto_now=True, verbose_name=' زمان ویرایش')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-order_metric',),
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=9, max_digits=4)),
            ],
            options={
                'verbose_name': 'نرخ مالیات بر ارزش افزوده',
                'verbose_name_plural': 'نرخ مالیات بر ارزش افزوده',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qty', models.PositiveBigIntegerField(verbose_name='تعداد')),
                ('is_scanned', models.BooleanField(default=False, verbose_name='اسکن شده')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_tourist', models.BooleanField(default=False, verbose_name='بلیط توریستی')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'بلیت',
                'verbose_name_plural': 'بلیت ها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('pc', 'pc pos'), ('cash', 'نقدی'), ('card', 'کارتی')], default='card', max_length=10, verbose_name='نوع تراکنش')),
                ('is_success', models.BooleanField(default=False, verbose_name='تراکنش موفق')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ تراکنش')),
                ('trans_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='شماره تراکنش')),
                ('date', models.CharField(blank=True, max_length=128, null=True, verbose_name='زمان تراکنش')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('has_tax', models.BooleanField(default=False, verbose_name='با احتساب ارزش افزورده')),
                ('discount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ تخفیف')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('products', models.ManyToManyField(related_name='categories', to='Amusement_Park_Application.product')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='ReturnedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pc', 'pc pos'), ('cash', 'نقدی'), ('card', 'کارتی')], max_length=10, verbose_name='نوع خرید')),
                ('qty', models.PositiveBigIntegerField(verbose_name='تعداد')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ تراکنش')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_sale', to='Amusement_Park_Application.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'برگشت از فروش',
                'verbose_name_plural': 'برگشت از فروش',
            },
        ),
    ]
