# Generated by Django 5.1.4 on 2025-01-15 11:11

import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('first_purchase', models.DateTimeField(auto_now_add=True, verbose_name='اولین خرید')),
                ('last_purchase', models.DateTimeField(auto_now=True, verbose_name='آخرین خرید')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('activate_time', models.CharField(choices=[('24 ساعت', '24 ساعت'), ('48 ساعت', '48 ساعت'), ('یک هفته', 'یک هفته'), ('یک ماه', 'یک ماه')], max_length=255, verbose_name='اعتبار')),
                ('activate', models.BooleanField(default=True, verbose_name='فعال')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان ها',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('persent', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('code', models.CharField(max_length=50, verbose_name='کد تخفیف')),
                ('activate', models.BooleanField(default=True, verbose_name='فعال')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True, verbose_name='نام محصول')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(help_text='لطفا سایز عکس ۱*۱ باشد تا دیزاین سایت زیباتر باشد', upload_to='product_image/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('is_taxable', models.BooleanField(default=True, editable=False, verbose_name='مشمول مالیات بر ارزش افزوده')),
                ('order_metric', models.PositiveIntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=' زمان ایجاد')),
                ('update', models.DateTimeField(auto_now=True, verbose_name=' زمان ویرایش')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-order_metric',),
            },
        ),
        migrations.CreateModel(
            name='RerecordingTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد رهگیری فروش مجدد')),
                ('type', models.CharField(choices=[('pc', 'pc pos'), ('cash', 'نقدی'), ('card', 'کارتی')], default='pc', max_length=10, verbose_name='نوع تراکنش')),
                ('is_success', models.BooleanField(default=True, help_text='این فیلد را نیازی نیست حذف کنید فقط تیک این فیلد را بردارید', verbose_name='تراکنش موفق')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'فروش مجدد',
                'verbose_name_plural': 'فروش های مجدد',
            },
        ),
        migrations.CreateModel(
            name='ReturnedTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد رهگیری عودت وجه')),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('نقد', 'نقد'), ('کارت به کارت', 'کارت به کارت'), ('انتقال با شماره شبا', 'انتقال با شماره شبا')], default='نقد', max_length=55, verbose_name='نوع عودت وجه')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('source_card_holder_name', models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=128, null=True, verbose_name='نام صاحب کارت مبدا')),
                ('destination_card_holder_name', models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=128, null=True, verbose_name='نام صاحب کارت مقصد')),
                ('source_card_number', models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=16, null=True, verbose_name='شماره کارت مبدا')),
                ('destination_card_number', models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=16, null=True, verbose_name='شماره کارت مقصد')),
                ('source_sheba_number', models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=24, null=True, verbose_name='شماره شبا مبدا')),
                ('destination_sheba_number', models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=24, null=True, verbose_name='شماره شبا مقصد')),
            ],
            options={
                'verbose_name': 'عودت وجه',
                'verbose_name_plural': 'عودت وجه',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(help_text='این متن در پیامک برای مشتری ارسال می شود', verbose_name='توضیحات')),
                ('target', models.CharField(blank=True, choices=[('کل مشتری ها', 'کل مشتری ها'), ('تولد ها', 'تولد ها'), ('مشتری های توریست', 'مشتری های توریست'), ('دهه هشتادی ها', 'دهه هشتادی ها'), ('دهه هفتادی ها', 'دهه هفتادی ها'), ('شماره های 0912', 'شماره های 0912'), ('تاپ تن مشتری های پرخرید', 'تاپ تن مشتری های پرخرید'), ('۱۰۰ مشتری پرخرید اول', '۱۰۰ مشتری پرخرید اول'), ('خرید اول', 'خرید اول'), ('خرید دهم', 'خرید دهم'), ('خرید صدم', 'خرید صدم'), ('سال نو', 'سال نو'), ('یلدا', 'یلدا'), ('تولد ها (پیام به آنهایی که تولدشان امروزه)', 'تولد ها (پیام به آنهایی که تولدشان امروزه)'), ('سیزده بدر', 'سیزده بدر'), ('آغاز تابستان', 'آغاز تابستان'), ('آغاز پاییز', 'آغاز پاییز'), ('آغاز زمستان', 'آغاز زمستان')], max_length=55, null=True, verbose_name='جامعه هدف')),
                ('activate', models.BooleanField(default=True, verbose_name='فعال')),
                ('j_create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پنل پیامکی',
                'verbose_name_plural': 'پنل پیامکی',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
            ],
            options={
                'verbose_name': 'مالیات',
                'verbose_name_plural': 'مالیات',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_scanned', models.BooleanField(default=False, verbose_name='اسکن شده')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'بلیت',
                'verbose_name_plural': 'بلیت ها',
            },
        ),
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
            ],
            options={
                'verbose_name_plural': 'محصولات بلیت',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد رهگیری فروش')),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('pc', 'pc pos'), ('cash', 'نقدی'), ('card', 'کارتی')], default='pc', max_length=10, verbose_name='نوع تراکنش')),
                ('is_success', models.BooleanField(default=True, help_text='این فروش را نیازی نیست حذف کنید فقط تیک این فیلد را بردارید', verbose_name='تراکنش موفق')),
                ('has_tax', models.BooleanField(default=True, verbose_name='با احتساب مالیات بر ارزش افزورده')),
                ('manual_discount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تخفیف دستی')),
                ('product_prices', models.IntegerField(verbose_name='مجموع مبلغ محصولات')),
                ('tax', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ مالیات')),
                ('discount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ تخفیف')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت نهایی')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت تراکنش')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('products', models.ManyToManyField(related_name='categories', to='Amusement_Park_Application.product')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
    ]
