# Generated by Django 5.1.4 on 2025-01-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Amusement_Park_Application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rerecordingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AddField(
            model_name='returnedtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='Amusement_Park_Application.customer', verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AddField(
            model_name='ticketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_products', to='Amusement_Park_Application.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='ticketproduct',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_products', to='Amusement_Park_Application.ticket', verbose_name='بلیت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Amusement_Park_Application.offer', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_obj', to='Amusement_Park_Application.ticket', verbose_name='بلیت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transaction',
            field=models.ManyToManyField(related_name='tickets', to='Amusement_Park_Application.transaction', verbose_name='تراکنش ها'),
        ),
        migrations.AddField(
            model_name='returnedtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_transaction', to='Amusement_Park_Application.transaction', verbose_name='کد رهگیری فروش'),
        ),
        migrations.AddField(
            model_name='rerecordingtransaction',
            name='rerecording_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rerecording', to='Amusement_Park_Application.transaction', verbose_name='کد رهگیری تراکنش مادر'),
        ),
    ]
