# Generated by Django 5.1.4 on 2025-01-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_taxable',
            field=models.BooleanField(default=True, verbose_name='مشمول مالیات بر ارزش افزوده'),
        ),
    ]
