# Generated by Django 5.1.4 on 2025-01-03 11:36

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('first_purchase', models.DateTimeField(auto_now_add=True, verbose_name='اولین خرید')),
                ('last_purchase', models.DateTimeField(auto_now=True, verbose_name='آخرین خرید')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('activate_time', models.CharField(choices=[('24 ساعت', '24 ساعت'), ('48 ساعت', '48 ساعت'), ('یک هفته', 'یک هفته'), ('یک ماه', 'یک ماه')], max_length=255, verbose_name='اعتبار')),
                ('activate', models.BooleanField(default=True, verbose_name='فعال')),
                ('set_up_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان ها',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('persent', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('code', models.CharField(max_length=50, verbose_name='کد تخفیف')),
                ('activate', models.BooleanField(default=True, verbose_name='فعال')),
                ('set_up_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(help_text='این متن در پیامک برای مشتری ارسال می شود', verbose_name='توضیحات')),
                ('target', models.CharField(blank=True, max_length=55, null=True, verbose_name='جامعه هدف')),
                ('activate', models.BooleanField(default=True, verbose_name='فعال')),
                ('set_up_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پنل پیامکی',
                'verbose_name_plural': 'پنل پیامکی',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عودت وجه')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('refund_price', models.PositiveBigIntegerField(verbose_name='مبلغ برگشتی')),
                ('transaction_type', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارتی'), ('both', 'پوز')], max_length=255, verbose_name='نوع تراکش')),
                ('refund_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='Amusement_Park_Application.transaction', verbose_name='تراکنش')),
                ('ticket_tracking_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='Amusement_Park_Application.ticket', verbose_name='کد رهگیری بلیت')),
            ],
        ),
        migrations.CreateModel(
            name='RefundProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_products', to='Amusement_Park_Application.product', verbose_name='محصول')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_products', to='Amusement_Park_Application.refund', verbose_name='عودت وجه')),
            ],
        ),
    ]
