# Generated by Django 5.1.4 on 2025-01-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activate_time',
            field=models.CharField(choices=[('1 ساعت', '1 ساعت'), ('24 ساعت', '24 ساعت'), ('48 ساعت', '48 ساعت'), ('یک هفته', 'یک هفته'), ('یک ماه', 'یک ماه')], max_length=255, verbose_name='اعتبار'),
        ),
    ]
