# Generated by Django 5.1.4 on 2025-01-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0003_alter_notification_activate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='activate',
            field=models.BooleanField(default=True, help_text='نکته مهم : تمام حروف ها باید انگلیسی و کوچک باشد', verbose_name='فعال'),
        ),
    ]
