# Generated by Django 5.1.4 on 2025-01-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0003_costumer_notification_offer_sms_refund_refundproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'عودت وجه', 'verbose_name_plural': 'عودت وجه ها'},
        ),
        migrations.AlterModelOptions(
            name='refundproduct',
            options={'verbose_name_plural': 'محصولات عودت وجه داده شده'},
        ),
    ]
