# Generated by Django 5.1.4 on 2025-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0003_alter_product_is_taxable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='manual_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف دستی'),
        ),
    ]
