# Generated by Django 5.1.4 on 2025-01-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0004_alter_transaction_manual_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='manual_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف دستی'),
        ),
    ]
