# Generated by Django 5.1.4 on 2025-01-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0004_alter_refund_options_alter_refundproduct_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveBigIntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Amusement_Park_Application.product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_products', to='Amusement_Park_Application.ticket')),
            ],
        ),
    ]
