# Generated by Django 5.1.4 on 2025-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0004_alter_offer_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(help_text='نکته مهم : تمام حروف ها باید انگلیسی و کوچک باشد', max_length=50, verbose_name='کد تخفیف'),
        ),
    ]
