# Generated by Django 5.1.4 on 2025-01-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0005_ticketproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketproduct',
            options={'verbose_name': 'محصول بلیت', 'verbose_name_plural': 'محصولات بلیت'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qty',
        ),
        migrations.AlterField(
            model_name='ticketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_products', to='Amusement_Park_Application.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='ticketproduct',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_products', to='Amusement_Park_Application.ticket', verbose_name='بلیت'),
        ),
    ]
