# Generated by Django 5.1.4 on 2025-01-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0005_alter_offer_activate_alter_offer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mix_cash',
            field=models.PositiveBigIntegerField(blank=True, help_text='در صورتی که نوع فروش ترکیبی باشد این فیلد به صورت اتوماتیک دریافت میشود', null=True, verbose_name='مقدار قیمت پرداخت شده نقدی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mix_pc',
            field=models.PositiveBigIntegerField(blank=True, help_text='در صورتی که نوع فروش ترکیبی باشد این فیلد به صورت اتوماتیک دریافت میشود', null=True, verbose_name='مقدار قیمت پرداخت شده با دستگاه کارتخوان'),
        ),
        migrations.AlterField(
            model_name='rerecordingtransaction',
            name='type',
            field=models.CharField(choices=[('pc', 'دستگاه کارتخوان'), ('cash', 'نقدی'), ('mix', 'ترکیبی')], default='pc', max_length=10, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_prices',
            field=models.PositiveBigIntegerField(verbose_name='مجموع مبلغ محصولات'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('pc', 'دستگاه کارتخوان'), ('cash', 'نقدی'), ('mix', 'ترکیبی')], default='pc', max_length=10, verbose_name='نوع تراکنش'),
        ),
    ]
