# Generated by Django 5.1.4 on 2025-02-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0007_rerecordingtransaction_mix_cash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'نوتیفیکیشن', 'verbose_name_plural': 'نوتیفیکیشن ها'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='activate_time',
        ),
    ]
