# Generated by Django 5.1.4 on 2025-01-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0007_alter_ticketproduct_options_remove_ticketproduct_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketproduct',
            options={'verbose_name_plural': 'محصولات بلیت'},
        ),
    ]
