# Generated by Django 5.1.4 on 2025-01-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0008_alter_ticketproduct_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='costumer',
            new_name='customer',
        ),
    ]
