# Generated by Django 5.1.4 on 2025-01-07 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0008_alter_sms_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rerecordingtransaction',
            name='rerecording_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rerecording', to='Amusement_Park_Application.transaction', verbose_name='کد رهگیری تراکنش'),
        ),
        migrations.AlterField(
            model_name='rerecordingtransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rerecording_transactions', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
    ]
