# Generated by Django 5.0.2 on 2025-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0008_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproduct',
            name='is_scanned',
            field=models.BooleanField(default=False, verbose_name='اسکن'),
        ),
    ]
