# Generated by Django 5.1.4 on 2025-01-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0009_rename_costumer_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedsale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='returnedsale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnedsale',
            name='qty',
        ),
        migrations.AddField(
            model_name='returnedsale',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='return_sale', to='Amusement_Park_Application.ticket', verbose_name='بلیت'),
            preserve_default=False,
        ),
    ]
