# Generated by Django 5.0.2 on 2025-02-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0009_ticketproduct_is_scanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketproduct',
            name='is_scanned',
        ),
        migrations.AddField(
            model_name='ticketproduct',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
    ]
