# Generated by Django 5.1.4 on 2025-01-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0010_remove_returnedsale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundproduct',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='refundproduct',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='returnedsale',
            options={'verbose_name': 'عودت وجه', 'verbose_name_plural': 'عودت وجه'},
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='RefundProduct',
        ),
    ]
