# Generated by Django 5.1.4 on 2025-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0010_alter_rerecordingtransaction_rerecording_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rerecordingtransaction',
            name='is_success',
            field=models.BooleanField(default=True, help_text='این فیلد را نیازی نیست حذف کنید فقط تیک این فیلد را بردارید', verbose_name='تراکنش موفق'),
        ),
        migrations.AlterField(
            model_name='returnedtransaction',
            name='is_success',
            field=models.BooleanField(default=True, help_text='این فیلد را نیازی نیست حذف کنید فقط تیک این فیلد را بردارید', verbose_name='تراکنش موفق'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_success',
            field=models.BooleanField(default=True, help_text='این فیلد را نیازی نیست حذف کنید فقط تیک این فیلد را بردارید', verbose_name='تراکنش موفق'),
        ),
    ]
