# Generated by Django 5.0.2 on 2025-02-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0010_remove_ticketproduct_is_scanned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketproduct',
            name='is_used',
        ),
        migrations.AddField(
            model_name='ticketproduct',
            name='scanned',
            field=models.BooleanField(default=False, verbose_name='اسکن شده'),
        ),
    ]
