# Generated by Django 5.1.4 on 2025-01-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0011_remove_refundproduct_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedsale',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_sale', to='Amusement_Park_Application.ticketproduct', verbose_name='بلیت'),
        ),
        migrations.AlterField(
            model_name='returnedsale',
            name='type',
            field=models.CharField(choices=[('pc', 'pc pos'), ('cash', 'نقدی'), ('card', 'کارتی')], max_length=10, verbose_name='نوع عودت وجه'),
        ),
    ]
