# Generated by Django 5.0.2 on 2025-02-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0011_remove_ticketproduct_is_used_ticketproduct_scanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_scanned',
        ),
    ]
