# Generated by Django 5.1.4 on 2025-01-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0011_alter_rerecordingtransaction_is_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rerecordingtransaction',
            name='rerecording_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rerecording', to='Amusement_Park_Application.transaction', verbose_name='کد رهگیری تراکنش'),
        ),
    ]
