# Generated by Django 5.1.4 on 2025-01-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0012_alter_rerecordingtransaction_rerecording_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedtransaction',
            name='is_success',
        ),
    ]
