# Generated by Django 5.1.4 on 2025-01-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0012_alter_returnedsale_ticket_alter_returnedsale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_obj', to='Amusement_Park_Application.ticketproduct', verbose_name='بلیت'),
        ),
    ]
