# Generated by Django 5.0.2 on 2025-02-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0012_remove_ticket_is_scanned'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardReaderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_mode', models.BooleanField(default=False, verbose_name='عملکرد به عنوان دستگاه کارتخوان')),
                ('serial', models.CharField(max_length=100, verbose_name='شماره سریال')),
                ('merchant', models.CharField(max_length=100, verbose_name='شماره پذیرنده')),
                ('terminal', models.CharField(max_length=100, verbose_name='شماره ترمینال')),
                ('ip', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
                ('port', models.PositiveIntegerField(verbose_name='شماره پورت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name_plural': 'دستگاه های کارتخوان',
            },
        ),
        migrations.AlterModelOptions(
            name='rerecordingtransaction',
            options={'verbose_name': 'تراکنش مجدد', 'verbose_name_plural': 'تراکنش های مجدد'},
        ),
    ]
