# Generated by Django 5.1.4 on 2025-01-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0013_remove_returnedtransaction_is_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={'verbose_name': 'مالیات', 'verbose_name_plural': 'مالیات'},
        ),
    ]
