# Generated by Django 5.1.4 on 2025-01-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0013_alter_transaction_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedsale',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_sale', to='Amusement_Park_Application.ticket', verbose_name='بلیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_obj', to='Amusement_Park_Application.ticket', verbose_name='بلیت'),
        ),
    ]
