# Generated by Django 5.0.2 on 2025-02-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0013_cardreadersetting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardReaderSetting',
        ),
    ]
