# Generated by Django 5.1.4 on 2025-01-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0014_alter_returnedsale_ticket_alter_transaction_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='Amusement_Park_Application.offer', verbose_name='تخفیف'),
        ),
    ]
