# Generated by Django 5.1.6 on 2025-03-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0014_delete_cardreadersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('noraml', 'عادی'), ('Tourist', 'توریستی')], default='noraml', max_length=10, verbose_name='نوع محصول'),
        ),
    ]
