# Generated by Django 5.1.4 on 2025-01-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0014_alter_taxrate_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='set_up_time',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='set_up_time',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='set_up_time',
            new_name='create_at',
        ),
    ]
