# Generated by Django 5.1.6 on 2025-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0015_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('noraml', 'عادی'), ('tourist', 'توریستی')], default='noraml', max_length=10, verbose_name='نوع محصول'),
        ),
    ]
