# Generated by Django 5.1.4 on 2025-01-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0015_ticket_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='offer',
        ),
    ]
