# Generated by Django 5.1.4 on 2025-01-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0015_rename_set_up_time_notification_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='target',
            field=models.CharField(blank=True, choices=[('کل مشتری ها', 'کل مشتری ها'), ('تولد ها', 'تولد ها'), ('مشتری های توریست', 'مشتری های توریست'), ('دهه هشتادی ها', 'دهه هشتادی ها'), ('دهه هفتادی ها', 'دهه هفتادی ها'), ('شماره های 0912', 'شماره های 0912'), ('تاپ تن مشتری های پرخرید', 'تاپ تن مشتری های پرخرید'), ('۱۰۰ مشتری پرخرید اول', '۱۰۰ مشتری پرخرید اول'), ('خرید اول', 'خرید اول'), ('خرید دهم', 'خرید دهم'), ('خرید صدم', 'خرید صدم'), ('سال نو', 'سال نو'), ('یلدا', 'یلدا'), ('تولد ها (پیام به آنهایی که تولدشان امروزه)', 'تولد ها (پیام به آنهایی که تولدشان امروزه)'), ('سیزده بدر', 'سیزده بدر'), ('آغاز تابستان', 'آغاز تابستان'), ('آغاز پاییز', 'آغاز پاییز'), ('آغاز زمستان', 'آغاز زمستان')], max_length=55, null=True, verbose_name='جامعه هدف'),
        ),
    ]
