# Generated by Django 5.1.6 on 2025-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0016_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='نام محصول به عربی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='نام محصول به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('normal', 'عادی'), ('tourist', 'توریستی')], default='normal', max_length=10, verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='نام محصول به فارسی'),
        ),
    ]
