# Generated by Django 5.1.4 on 2025-01-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0016_alter_sms_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedtransaction',
            name='is_success',
            field=models.BooleanField(default=True, help_text='این فیلد را نیازی نیست حذف کنید فقط تیک این فیلد را بردارید', verbose_name='تراکنش موفق'),
        ),
    ]
