# Generated by Django 5.1.4 on 2025-01-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0016_remove_ticket_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSaleReport',
        ),
    ]
