# Generated by Django 5.1.6 on 2025-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0017_product_title_ar_product_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کشور'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='جنسیت'),
        ),
    ]
