# Generated by Django 5.1.4 on 2025-01-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0017_returnedtransaction_is_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedtransaction',
            name='is_success',
        ),
    ]
