# Generated by Django 5.1.6 on 2025-05-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0018_customer_city_customer_contry_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contry',
            new_name='country',
        ),
    ]
