# Generated by Django 5.1.4 on 2025-01-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0018_remove_returnedtransaction_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedtransaction',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Amusement_Park_Application.transaction'),
        ),
    ]
