# Generated by Django 5.1.4 on 2025-01-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0019_alter_returnedtransaction_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_transaction', to='Amusement_Park_Application.transaction', verbose_name='کد رهگیری فروش'),
        ),
    ]
