# Generated by Django 5.1.4 on 2025-01-04 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0019_delete_salessummarybycustomer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Amusement_Park_Application.offer', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_prices',
            field=models.PositiveBigIntegerField(default=1, verbose_name='مجموع مبلغ محصولات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ مالیات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='لطفا سایز عکس ۱*۱ باشد تا دیزاین سایت زیباتر باشد', upload_to='product_image/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='has_tax',
            field=models.BooleanField(default=True, verbose_name='با احتساب مالیات بر ارزش افزورده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_success',
            field=models.BooleanField(default=True, verbose_name='تراکنش موفق'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد رهگیری فروش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('pc', 'pc pos'), ('cash', 'نقدی'), ('card', 'کارتی')], default='pc', max_length=10, verbose_name='نوع تراکنش'),
        ),
    ]
