# Generated by Django 5.1.6 on 2025-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0019_rename_contry_customer_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyTransactionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات فروش آماده')),
            ],
            options={
                'verbose_name': 'توضیحات فروش آماده',
                'verbose_name_plural': 'توضیحات فروش آماده',
            },
        ),
    ]
