# Generated by Django 5.1.6 on 2025-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0020_readytransactioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readytransactioninfo',
            name='desc',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='توضیحات فروش آماده'),
        ),
    ]
