# Generated by Django 5.1.4 on 2025-01-04 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0020_remove_transaction_date_remove_transaction_trans_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='کد رهگیری فروش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
