# Generated by Django 5.1.4 on 2025-01-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0020_alter_returnedtransaction_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amusement_Park_Application.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amusement_Park_Application.transaction')),
            ],
            options={
                'verbose_name': 'گزارش فروش به تفکیک محصول',
                'verbose_name_plural': 'گزارش فروش به تفکیک محصول',
            },
        ),
    ]
