# Generated by Django 5.1.6 on 2025-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0021_alter_readytransactioninfo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='auto_percent_discount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
    ]
