# Generated by Django 5.1.4 on 2025-01-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0021_productsalereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Amusement_Park_Application.transaction',),
        ),
        migrations.DeleteModel(
            name='ProductSaleReport',
        ),
        migrations.CreateModel(
            name='ProductSaleReport',
            fields=[
            ],
            options={
                'verbose_name': 'گزارش فروش به تفکیک محصول',
                'verbose_name_plural': 'گزارش فروش به تفکیک محصول',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Amusement_Park_Application.transaction',),
        ),
    ]
