# Generated by Django 5.1.4 on 2025-01-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0021_alter_transaction_id_alter_transaction_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RerecordingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pc', 'pc pos'), ('cash', 'نقدی'), ('card', 'کارتی')], default='pc', max_length=10, verbose_name='نوع تراکنش')),
                ('is_success', models.BooleanField(default=True, verbose_name='تراکنش موفق')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('rerecording_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rerecording', to='Amusement_Park_Application.transaction', verbose_name='کد رهگیری تراکنش')),
            ],
            options={
                'verbose_name': 'تراکنش مجدد',
                'verbose_name_plural': 'تراکنش های مجدد',
            },
        ),
    ]
