# Generated by Django 5.1.4 on 2025-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0022_rerecordingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedsale',
            name='is_success',
            field=models.BooleanField(default=True, verbose_name='تراکنش موفق'),
        ),
    ]
