# Generated by Django 5.1.4 on 2025-01-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0022_sale_delete_productsalereport_productsalereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSaleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ticket_qty', models.PositiveIntegerField(default=0, verbose_name='تعداد بلیط')),
                ('total_sales_qty', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('total_sales_value', models.BigIntegerField(default=0, verbose_name='جمع کل فروش - ریال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_results', to='Amusement_Park_Application.product', verbose_name='نام محصول')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductSaleReport',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
