# Generated by Django 5.1.4 on 2025-01-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0023_returnedsale_is_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulTransactionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد رهگیری تراکنش')),
                ('transaction_id', models.IntegerField(verbose_name='کد تراکنش')),
                ('kind', models.CharField(choices=[('Transaction', 'فروش'), ('RerecordingTransaction', 'فروش مجدد'), ('ReturnedSale', 'عودت وجه')], max_length=30, verbose_name='نوع تراکنش')),
                ('is_success', models.BooleanField(default=True, verbose_name='تراکنش موفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'ثبت تراکنش موفق',
                'verbose_name_plural': 'ثبت تراکنش های موفق',
            },
        ),
    ]
