# Generated by Django 5.1.4 on 2025-01-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0023_productsaleresult_delete_productsalereport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSaleResult',
        ),
    ]
