# Generated by Django 5.1.6 on 2025-06-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0023_transaction_auto_percent_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='auto_percent_tax',
            field=models.PositiveBigIntegerField(default=0, verbose_name='درصد مالیات'),
        ),
    ]
