# Generated by Django 5.1.4 on 2025-01-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0025_remove_successfultransactionlog_is_success_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successfultransactionlog',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
