# Generated by Django 5.1.4 on 2025-01-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0026_rename_created_at_successfultransactionlog_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successfultransactionlog',
            name='kind',
            field=models.CharField(choices=[('فروش', 'Transaction'), ('فروش مجدد', 'RerecordingTransaction'), ('عودت وجه', 'ReturnedSale')], max_length=30, verbose_name='نوع تراکنش'),
        ),
    ]
