# Generated by Django 5.1.4 on 2025-01-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0027_alter_successfultransactionlog_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rerecordingtransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rerecording_transactions', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AlterField(
            model_name='returnedsale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_sales', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
    ]
