# Generated by Django 5.1.6 on 2025-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0028_alter_transaction_auto_percent_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='auto_percent_discount',
            field=models.PositiveBigIntegerField(default=0, help_text='درصد این فیلد از فیلد ("مجموع مبلغ محصولات" + "مبلغ مالیات") گرفته میشود', verbose_name='درصد تخفیف'),
        ),
    ]
