# Generated by Django 5.1.4 on 2025-01-04 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0028_rerecordingtransaction_user_alter_returnedsale_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.DeleteModel(
            name='SuccessfulTransactionLog',
        ),
    ]
