# Generated by Django 5.1.4 on 2025-01-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0029_alter_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedsale',
            name='destination_card_holder_name',
            field=models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=128, null=True, verbose_name='نام صاحب کارت مقصد'),
        ),
        migrations.AddField(
            model_name='returnedsale',
            name='destination_card_number',
            field=models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=16, null=True, verbose_name='شماره کارت مقصد'),
        ),
        migrations.AddField(
            model_name='returnedsale',
            name='destination_sheba_number',
            field=models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=24, null=True, verbose_name='شماره شبا مقصد'),
        ),
        migrations.AddField(
            model_name='returnedsale',
            name='source_card_holder_name',
            field=models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=128, null=True, verbose_name='نام صاحب کارت مبدا'),
        ),
        migrations.AddField(
            model_name='returnedsale',
            name='source_card_number',
            field=models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=16, null=True, verbose_name='شماره کارت مبدا'),
        ),
        migrations.AddField(
            model_name='returnedsale',
            name='source_sheba_number',
            field=models.CharField(blank=True, help_text='درصورتی که نوع عودت وجه را از طریق شماره کارت یا شماره شبا انتخاب کرده اید این فیلد را پر کنید', max_length=24, null=True, verbose_name='شماره شبا مبدا'),
        ),
        migrations.AlterField(
            model_name='returnedsale',
            name='type',
            field=models.CharField(choices=[('نقد', 'نقد'), ('کارت به کارت', 'کارت به کارت'), ('انتقال با شماره شبا', 'انتقال با شماره شبا')], default='نقد', max_length=55, verbose_name='نوع عودت وجه'),
        ),
    ]
