# Generated by Django 5.1.4 on 2025-01-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0030_returnedsale_destination_card_holder_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulTransactionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد رهگیری تراکنش')),
                ('kind', models.CharField(choices=[('Transaction', 'فروش'), ('RerecordingTransaction', 'فروش مجدد'), ('ReturnedSale', 'عودت وجه')], max_length=30, verbose_name='نوع تراکنش')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successful_sales', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'ثبت تراکنش موفق',
                'verbose_name_plural': 'ثبت تراکنش های موفق',
            },
        ),
    ]
