# Generated by Django 5.1.6 on 2025-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0031_alter_transaction_auto_percent_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='auto_percent_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='درصد این فیلد از فیلد ("مجموع مبلغ محصولات" + "مبلغ مالیات") گرفته میشود', max_digits=5, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='auto_percent_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='درصد این فیلد از فیلد "مجموع مبلغ محصولات" گرفته میشود', max_digits=5, verbose_name='درصد مالیات'),
        ),
    ]
