# Generated by Django 5.1.4 on 2025-01-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0033_alter_successfultransactionlog_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'فروش های موفق', 'verbose_name_plural': 'فروش های موفق'},
        ),
        migrations.AlterModelOptions(
            name='successfultransactionlog',
            options={'verbose_name': 'تراکنش ها', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'فروش', 'verbose_name_plural': 'فروش ها'},
        ),
    ]
