# Generated by Django 5.1.6 on 2025-06-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0033_alter_transaction_auto_percent_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_amount', models.PositiveBigIntegerField(verbose_name='مجموع قیمت دستگاه کارتخوان')),
                ('cash_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مجموع قیمت صندوق (نقد)')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'گزارش فروش روزانه',
                'verbose_name_plural': 'گزارش فروش روزانه',
            },
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'بلیط', 'verbose_name_plural': 'بلیط ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketproduct',
            options={'verbose_name_plural': 'محصولات بلیط'},
        ),
        migrations.AlterField(
            model_name='ticketproduct',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_products', to='Amusement_Park_Application.ticket', verbose_name='بلیط'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_obj', to='Amusement_Park_Application.ticket', verbose_name='بلیط'),
        ),
    ]
