# Generated by Django 5.1.6 on 2025-06-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0034_salesreport_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت ریپورت به تاریخ میلادی'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان آپدیت ریپورت به تاریخ میلادی'),
        ),
    ]
