# Generated by Django 5.1.4 on 2025-01-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0034_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rerecordingtransaction',
            options={'verbose_name': 'فروش مجدد', 'verbose_name_plural': 'فروش های مجدد'},
        ),
    ]
