# Generated by Django 5.1.4 on 2025-01-05 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0035_alter_rerecordingtransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfultransactionlog',
            name='rerecording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amusement_Park_Application.rerecordingtransaction', verbose_name='فروش مجدد'),
        ),
        migrations.AddField(
            model_name='successfultransactionlog',
            name='returned_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amusement_Park_Application.returnedsale', verbose_name='عودت وجه'),
        ),
        migrations.AddField(
            model_name='successfultransactionlog',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amusement_Park_Application.sale', verbose_name='فروش'),
        ),
        migrations.AlterField(
            model_name='rerecordingtransaction',
            name='rerecording_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rerecording', to='Amusement_Park_Application.transaction', verbose_name='کد رهگیری تراکنش مادر'),
        ),
    ]
