# Generated by Django 5.1.4 on 2025-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0036_successfultransactionlog_rerecording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rerecordingtransaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='کد رهگیری فروش مجدد'),
        ),
        migrations.AlterField(
            model_name='returnedsale',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='کد رهگیری عودت وجه'),
        ),
    ]
