# Generated by Django 5.1.6 on 2025-06-16 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0036_rename_created_at_salesreport_create_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=55, verbose_name='نوع وسیله فروش')),
            ],
            options={
                'verbose_name': 'نوع وسیله فروش',
                'verbose_name_plural': 'نوع وسیله فروش',
            },
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='pos_amount',
        ),
        migrations.AddField(
            model_name='salesreport',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ فروش به ریال'),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Amusement_Park_Application.devicesalesreport', verbose_name='نوع وسیله فروش'),
        ),
    ]
