# Generated by Django 5.1.4 on 2025-01-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0037_alter_rerecordingtransaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedsale',
            name='ticket',
        ),
        migrations.AddField(
            model_name='returnedsale',
            name='sale',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='return_sale', to='Amusement_Park_Application.sale', verbose_name='کد رهگیری فروش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='successfultransactionlog',
            name='rerecording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amusement_Park_Application.rerecordingtransaction', verbose_name='کد رهگیری فروش مجدد'),
        ),
        migrations.AlterField(
            model_name='successfultransactionlog',
            name='returned_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amusement_Park_Application.returnedsale', verbose_name='کد رهگیری عودت وجه'),
        ),
        migrations.AlterField(
            model_name='successfultransactionlog',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amusement_Park_Application.sale', verbose_name='کد رهگیری فروش'),
        ),
    ]
