# Generated by Django 5.1.6 on 2025-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0037_devicesalesreport_remove_salesreport_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesalesreport',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات نوع وسیله فروش'),
        ),
    ]
