# Generated by Django 5.1.6 on 2025-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0038_devicesalesreport_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesalesreport',
            name='device_MID_number',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='شماره پذیرنده دستگاه'),
        ),
        migrations.AddField(
            model_name='devicesalesreport',
            name='device_compony',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='شرکت ارائه دهنده دستگاه'),
        ),
        migrations.AddField(
            model_name='devicesalesreport',
            name='device_serial_number',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='شماره سریال دستگاه'),
        ),
        migrations.AddField(
            model_name='devicesalesreport',
            name='device_terminal_number',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='شماره ترمینال دستگاه'),
        ),
        migrations.AlterField(
            model_name='devicesalesreport',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
