# Generated by Django 5.1.6 on 2025-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0039_devicesalesreport_device_mid_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesalesreport',
            name='device_connection_type',
            field=models.CharField(choices=[('دستی', 'دستی'), ('IP', 'IP'), ('کابل سریال', 'کابل سریال'), ('هیچکدام', 'هیچکدام')], default='هیچکدام', max_length=55, verbose_name='نوع عودت وجه'),
        ),
    ]
