# Generated by Django 5.1.6 on 2025-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0041_alter_devicesalesreport_device_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='amount',
            field=models.PositiveBigIntegerField(default=1, verbose_name='مبلغ فروش به ریال'),
        ),
    ]
