# Generated by Django 5.1.6 on 2025-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amusement_Park_Application', '0042_alter_salesreport_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ فروش به ریال'),
        ),
    ]
